project_name: ddns-client

builds:
  - binary: ddns-client

    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.appVersion={{.Version}}

    goos:
      - windows
      - darwin
      - linux
      - freebsd
      - openbsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7
      - 6

    ignore:
      - goos: darwin
        goarch: 386
      - goos: openbsd
        goarch: arm

archives:
  - replacements:
      386: i386
  - id: ddns-client
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
